### ISSUE TITLE
Bonus section is incomplete, toasts don't show

### ISSUE THREAD

**Issue by gkingston** [johnpapa/ngrx-data-lab#15]
The bonus section is missing the steps to add the NgrxDataToastService to the EntityStoreModule, which results in the toasts not showing. 

Farther up in the tutorial, the EntityStoreModule is replaced and includes no providers and an empty constructor.  Once the NgrxDataToastService is created, it needs to be added to the EntityStoreModule constructor and providers section.

**Comment by gkingston** [comment]
Pull request #14 should fix this.

**Comment by jberall** [comment]
I followed the directions and the snackbar aka toast doesn't show.

I think some code from the EntityStoreModule  constructor is missing

BTW, this project is super cool!
entity-store.module.ts
`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EntityMetadataMap, NgrxDataModule } from 'ngrx-data';
import { NgrxDataToastService } from './ngrx-data-toast.service';

export const entityMetadata: EntityMetadataMap = {
  Hero: {},
  Villain: {},
};

// because the plural of "hero" is not "heros"
export const pluralNames = { Hero: 'Heroes' };

@NgModule({
  imports: [
    CommonModule,
    NgrxDataModule.forRoot({
      entityMetadata: entityMetadata,
      pluralNames: pluralNames
    })
  ],
  declarations: [],
  providers: [NgrxDataToastService]
})
export class EntityStoreModule {}`

My Service
`
import { Injectable } from '@angular/core';
import { EntityActions, OP_ERROR, OP_SUCCESS } from 'ngrx-data';
import { ToastService } from '../core/toast.service';

/** Report ngrx-data success/error actions as toast messages **/
@Injectable()
export class NgrxDataToastService {
  constructor(actions$: EntityActions, toast: ToastService) {
    actions$
      .where(ea => ea.op.endsWith(OP_SUCCESS) || ea.op.endsWith(OP_ERROR))
      // this service never dies so no need to unsubscribe
      .subscribe(action =>
        toast.openSnackBar(`${action.entityName} action`, action.op)
      );
  }
}
`

**Comment by johnpapa** [comment]
thanks for adding this issue. 

we updated a lot here recently. i think this is resolved. if not, please reopen
